# https://taskfile.dev

version: '3'

vars:
  VARFILE: setup.tfvars

dotenv: ['.env', '{{.ENV}}/.env', '{{.HOME}}/.env']

includes:
  test:
    taskfile: ./taskfiles/test.yml

  infra:
    taskfile: ./taskfiles/infra.yml

tasks:
  install:
    cmds:
      - uv sync --group dev

  format:
    cmds:
      - uv run ruff format

  lint:
    cmds:
      - uv run ruff check --fix

  fix:
    cmds:
      - task: lint
      - task: format
